# Generated by Django 5.1.4 on 2025-03-22 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('region', models.CharField(choices=[('malaysia', 'Within Malaysia'), ('asia', 'Within Asia'), ('international', 'International')], max_length=100)),
                ('origin_country', models.CharField(blank=True, max_length=100)),
                ('destination_country', models.CharField(blank=True, max_length=100)),
                ('origin_address', models.TextField(blank=True)),
                ('destination_address', models.TextField(blank=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dimensions', models.CharField(max_length=50)),
                ('item_description', models.TextField()),
                ('shipping_method', models.CharField(max_length=50)),
                ('estimated_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_delivery_time', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quote_id', models.CharField(max_length=50, unique=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
