# Generated by Django 5.1.1 on 2025-05-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(choices=[('general', 'General Inquiry'), ('shipping', 'Shipping to Malaysia'), ('tracking', 'Package Tracking'), ('international', 'International Shipping'), ('feedback', 'Feedback'), ('other', 'Other')], default='general', max_length=50),
        ),
    ]
