# Generated by Django 5.1.1 on 2025-04-13 10:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package_weight', models.DecimalField(decimal_places=2, help_text='Weight in kg', max_digits=6, validators=[django.core.validators.MinLengthValidator(0.1)])),
                ('region', models.CharField(choices=[('Malaysia,', 'Malaysia'), ('Asia', 'Asia'), ('International', 'International')], max_length=20)),
                ('origin_state_country', models.CharField(max_length=100)),
                ('origin_address', models.TextField()),
                ('pick_up_point', models.CharField(blank=True, max_length=225, null=True)),
                ('pickup_contact_name', models.CharField(max_length=100)),
                ('pickup_contact_number', models.CharField(max_length=20)),
                ('destination_state_country', models.CharField(max_length=100)),
                ('destination_address', models.TextField()),
                ('destination_contact_name', models.CharField(max_length=100)),
                ('destination_contact_number', models.CharField(max_length=20)),
                ('shipping_method', models.CharField(choices=[('Standard', 'Standard'), ('Express', 'Express')], max_length=20)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('express_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
