# Generated by Django 5.1.1 on 2025-04-14 10:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='shippingorder',
            name='package_weight',
            field=models.DecimalField(decimal_places=2, help_text='Weight in kilograms (kg)', max_digits=6, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
    ]
