# Generated by Django 5.1.4 on 2025-05-18 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('order_id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('shipping_location', models.CharField(choices=[('MY', 'Malaysia'), ('AS', 'Asia'), ('INT', 'International')], max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('pickup_contact', models.CharField(max_length=255)),
                ('destination_location', models.CharField(max_length=255)),
                ('destination_contact', models.CharField(max_length=255)),
                ('shipping_type', models.CharField(choices=[('ST', 'Standard'), ('EX', 'Express')], max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
