# Generated by Django 5.1.1 on 2025-05-13 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_shippingorder_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingorder',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='shippingorder',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='shippingorder',
            name='express_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='shippingorder',
            name='region',
            field=models.CharField(choices=[('Malaysia', 'Malaysia'), ('Asia', 'Asia'), ('International', 'International')], max_length=20),
        ),
        migrations.AlterField(
            model_name='shippingorder',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
